### ISSUE TITLE
Onlinecensorship.org request to re-publish certain EFF blog posts

### ISSUE THREAD

**Issue by lenazun** [EFForg/onlinecensorship#136]
ref https://redmine.eff.org/issues/19383

Elliott let me know that there was a way to pull certain EFF blog posts
onto other blogs (i.e., the way we do with SEC) using tags. I'd like to
do this for Onlinecensorship.org with a special tag that would allow me
to select specific posts that fit the site's mandate.

Is this possible? I can commit to going in and doing the tagging myself.

**Comment by esoterik** [comment]
done in #138
